service: shifty-auth

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    JWT_SECRET: secret
    JWT_ALGORITHM: HS256
    USER_TABLE: Users
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USER_TABLE}"

functions:
  register:
    handler: handler.register
  login:
    handler: handler.login
  auth:
    handler: handler.authorizer

